name: Close Pull Request with custom comment
author: fotise
description: 'A GitHub Action for close pull requests, adding a custom comment'
branding:
  icon: 'alert-circle'
  color: green
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  message:
    description: 'Message displayed in pr comment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
