name: Approve Pull Request
author: fotise
description: 'A GitHub Action for close pull requests'
branding:
  icon: '2017'
  color: green
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  number:
    description: 'Pull Request number'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
