name: CLA
branding:
  icon: 'alert-circle'
  color: 'blue'
on: [push, pull_request]
jobs:
  checkForSignedCLA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Close Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
